# Generated by Django 4.2.4 on 2023-08-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_categories_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
