# Generated by Django 4.2.4 on 2023-10-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_categories_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
