# Generated by Django 4.2.4 on 2023-08-28 17:58

from django.db import migrations
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='media',
            field=django_enum.fields.EnumCharField(blank=True, choices=[('facebook', 'Facebooik'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('phone', 'Phone'), ('youtube', 'Youtube'), ('telephone', 'Telephone')], max_length=9, null=True),
        ),
    ]
