# Generated by Django 4.2.4 on 2023-08-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_contacts_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
